/*
 * CameraSettingsForm.java
 *
 * Created on July 12, 2007, 7:02 PM
 */

package demo.ui;

import javax.swing.JPanel;

/**
 *
 * @author  gestalt
 */
public class CameraSettingsForm extends JPanel
{

    public CameraSettingsBean getBoundBean()
    {
        return boundBean;
    }
    

    public CameraSettingsForm()
    {
        initComponents();
    }        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        final javax.swing.JLabel jResolutionLabel = new javax.swing.JLabel();
        final javax.swing.JLabel jFramerateLabel = new javax.swing.JLabel();
        final javax.swing.JLabel jFlipLabel = new javax.swing.JLabel();

        jResolutionLabel.setText("Resolution:");
        jResolutionLabel.setEnabled(false);

        jResolutionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1024 x 768" }));
        jResolutionComboBox.setEnabled(false);

        jFramerateLabel.setText("Framerate:");
        jFramerateLabel.setEnabled(false);

        jFramerateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30" }));
        jFramerateComboBox.setEnabled(false);

        jFlipLabel.setText("Flip:");

        jFlipHorizontalCheckBox.setText("horizontal");
        jFlipHorizontalCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jFlipVerticalCheckBox.setText("vertical");
        jFlipVerticalCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jResolutionLabel)
                    .addComponent(jFlipLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jResolutionComboBox, 0, 112, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jFramerateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFramerateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFlipHorizontalCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFlipVerticalCheckBox)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jResolutionLabel)
                    .addComponent(jFramerateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFramerateLabel)
                    .addComponent(jResolutionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFlipLabel)
                    .addComponent(jFlipHorizontalCheckBox)
                    .addComponent(jFlipVerticalCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final demo.ui.CameraSettingsBean boundBean = new demo.ui.CameraSettingsBean();
    private final javax.swing.JCheckBox jFlipHorizontalCheckBox = new javax.swing.JCheckBox();
    private final javax.swing.JCheckBox jFlipVerticalCheckBox = new javax.swing.JCheckBox();
    private final javax.swing.JComboBox jFramerateComboBox = new javax.swing.JComboBox();
    private final javax.swing.JComboBox jResolutionComboBox = new javax.swing.JComboBox();
    // End of variables declaration//GEN-END:variables
    
}
