/*
 * ImageProcessingForm.java
 *
 * Created on July 12, 2007, 7:15 PM
 */

package demo.ui;

import javax.swing.JPanel;

/**
 *
 * @author  gestalt
 */
public class ImageProcessingForm extends JPanel
{
    
    public ImageProcessingBean getBoundBean()
    {
        return boundBean;
    }
    

    public ImageProcessingForm()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        final javax.swing.JLabel jFrameSubLabel = new javax.swing.JLabel();
        final javax.swing.JLabel jThresholdLabel = new javax.swing.JLabel();

        jFrameSubLabel.setText("Frame Subtraction:");
        jFrameSubLabel.setEnabled(false);

        frameSubButtonGroup.add(jFrameSubNeverRadioButton);
        jFrameSubNeverRadioButton.setText("never");
        jFrameSubNeverRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jFrameSubNeverRadioButton.setEnabled(false);

        frameSubButtonGroup.add(jFrameSubOnceRadioButton);
        jFrameSubOnceRadioButton.setSelected(true);
        jFrameSubOnceRadioButton.setText("once");
        jFrameSubOnceRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jFrameSubOnceRadioButton.setEnabled(false);

        frameSubButtonGroup.add(jFrameSubAlwaysRadioButton);
        jFrameSubAlwaysRadioButton.setText("always");
        jFrameSubAlwaysRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jFrameSubAlwaysRadioButton.setEnabled(false);

        jThresholdSlider.setMajorTickSpacing(50);
        jThresholdSlider.setMaximum(255);
        jThresholdSlider.setMinorTickSpacing(5);
        jThresholdSlider.setPaintLabels(true);
        jThresholdSlider.setPaintTicks(true);

        jThresholdLabel.setText("Threshold:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jThresholdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jThresholdSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFrameSubLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jFrameSubNeverRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(jFrameSubOnceRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(jFrameSubAlwaysRadioButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFrameSubLabel)
                    .addComponent(jFrameSubAlwaysRadioButton)
                    .addComponent(jFrameSubOnceRadioButton)
                    .addComponent(jFrameSubNeverRadioButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jThresholdLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jThresholdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final demo.ui.ImageProcessingBean boundBean = new demo.ui.ImageProcessingBean();
    private final javax.swing.ButtonGroup frameSubButtonGroup = new javax.swing.ButtonGroup();
    private final javax.swing.JRadioButton jFrameSubAlwaysRadioButton = new javax.swing.JRadioButton();
    private final javax.swing.JRadioButton jFrameSubNeverRadioButton = new javax.swing.JRadioButton();
    private final javax.swing.JRadioButton jFrameSubOnceRadioButton = new javax.swing.JRadioButton();
    private final javax.swing.JSlider jThresholdSlider = new javax.swing.JSlider();
    // End of variables declaration//GEN-END:variables
    
}
