/*
 * Copyright (C) 2007 Deutsche Telekom AG Laboratories
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package demo.tuio;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Michael Nischt
 * @version 0.1
 */

class JServerPanel extends javax.swing.JPanel
{

    class Event extends java.util.EventObject
    {

        private boolean cancelled;

        Event()
        {
            super(JServerPanel.this);
        }

        public String getHost()
        {
            return JServerPanel.this.getHost();
        }

        public int getPort()
        {
            return JServerPanel.this.getPort();
        }

        public void cancel(String status)
        {
            jStatusLabel.setText(status);
            cancelled = true;
        }

        private boolean isCancelled()
        {
            return cancelled;
        }
    }

    static interface Listener extends java.util.EventListener
    {

        public void finished(Event e);

        public void cancelled(Event e);
    }

    public JServerPanel()
    {
        initComponents();
    }

    public String getHost()
    {
        return jHostTextField.getText();
    }

    public int getPort()
    {
        return (Integer) jPortSpinner.getValue();
    }

    public void addServerPanelListener(Listener l)
    {
        listeners.add(l);
    }

    public void removeServerPanelListener(Listener l)
    {
        listeners.add(l);
    }

    public Listener[] getServerPanelListener()
    {
        return listeners.toArray(new Listener[0]);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameSubButtonGroup = new javax.swing.ButtonGroup();
        javax.swing.JButton jOKButton = new javax.swing.JButton();
        javax.swing.JButton jCancelButton = new javax.swing.JButton();
        javax.swing.JPanel jAddressPanel = new javax.swing.JPanel();
        javax.swing.JLabel jHostLabel = new javax.swing.JLabel();
        javax.swing.JLabel jPortLabel = new javax.swing.JLabel();
        jPortSpinner = new javax.swing.JSpinner();
        javax.swing.JPanel jCameraPanel = new javax.swing.JPanel();
        javax.swing.JLabel jResolutionLabel = new javax.swing.JLabel();
        jResolutionComboBox = new javax.swing.JComboBox();
        javax.swing.JLabel jFlipLabel = new javax.swing.JLabel();
        javax.swing.JLabel jFramerateLabel = new javax.swing.JLabel();
        jFlipHorizontalCheckBox = new javax.swing.JCheckBox();
        jFlipVerticalCheckBox = new javax.swing.JCheckBox();
        javax.swing.JPanel jImageProcPanel = new javax.swing.JPanel();
        jThresholdLabel = new javax.swing.JLabel();
        jFrameSubLabel = new javax.swing.JLabel();
        jFrameSubNeverRadioButton = new javax.swing.JRadioButton();
        jFrameSubOnceRadioButton = new javax.swing.JRadioButton();
        jFrameSubAlwaysRadioButton = new javax.swing.JRadioButton();
        jThresholdSlider = new javax.swing.JSlider();

        jStatusLabel.setForeground(java.awt.Color.red);
        jStatusLabel.setText("     ");

        jOKButton.setText("OK");
        jOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKButtonActionPerformed(evt);
            }
        });

        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jAddressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Internet Socket Address ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null));

        jHostLabel.setLabelFor(jHostTextField);
        jHostLabel.setText("Host:");

        jHostTextField.setText("localhost");

        jPortLabel.setLabelFor(jPortSpinner);
        jPortLabel.setText("Port:");

        jPortSpinner.setModel(new javax.swing.SpinnerNumberModel(57110, 49152, 65535, 1));
        jPortSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(jPortSpinner, "#"));

        javax.swing.GroupLayout jAddressPanelLayout = new javax.swing.GroupLayout(jAddressPanel);
        jAddressPanel.setLayout(jAddressPanelLayout);
        jAddressPanelLayout.setHorizontalGroup(
            jAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jHostTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPortLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPortSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jAddressPanelLayout.setVerticalGroup(
            jAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHostLabel)
                    .addComponent(jPortSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPortLabel)
                    .addComponent(jHostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCameraPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Camera Settings ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null));

        jResolutionLabel.setLabelFor(jResolutionComboBox);
        jResolutionLabel.setText("Resolution:");

        jResolutionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1024 x 768" }));

        jFlipLabel.setText("Flip:");

        jFramerateLabel.setText("Framerate:");

        jFramerateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30" }));

        jFlipHorizontalCheckBox.setText("horizontal");
        jFlipHorizontalCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jFlipVerticalCheckBox.setText("vertical");
        jFlipVerticalCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.GroupLayout jCameraPanelLayout = new javax.swing.GroupLayout(jCameraPanel);
        jCameraPanel.setLayout(jCameraPanelLayout);
        jCameraPanelLayout.setHorizontalGroup(
            jCameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCameraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jResolutionLabel)
                    .addComponent(jFlipLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCameraPanelLayout.createSequentialGroup()
                        .addComponent(jResolutionComboBox, 0, 240, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jFramerateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFramerateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jCameraPanelLayout.createSequentialGroup()
                        .addComponent(jFlipHorizontalCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFlipVerticalCheckBox)))
                .addContainerGap())
        );
        jCameraPanelLayout.setVerticalGroup(
            jCameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCameraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jCameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jResolutionLabel)
                    .addComponent(jFramerateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFramerateLabel)
                    .addComponent(jResolutionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jCameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFlipLabel)
                    .addComponent(jFlipHorizontalCheckBox)
                    .addComponent(jFlipVerticalCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jImageProcPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Image Processing ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null));

        jThresholdLabel.setText("Threshold:");

        jFrameSubLabel.setText("Frame Subtraction:");

        frameSubButtonGroup.add(jFrameSubNeverRadioButton);
        jFrameSubNeverRadioButton.setText("never");
        jFrameSubNeverRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        frameSubButtonGroup.add(jFrameSubOnceRadioButton);
        jFrameSubOnceRadioButton.setSelected(true);
        jFrameSubOnceRadioButton.setText("once");
        jFrameSubOnceRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        frameSubButtonGroup.add(jFrameSubAlwaysRadioButton);
        jFrameSubAlwaysRadioButton.setText("always");
        jFrameSubAlwaysRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jThresholdSlider.setMajorTickSpacing(50);
        jThresholdSlider.setMaximum(255);
        jThresholdSlider.setMinorTickSpacing(5);
        jThresholdSlider.setPaintLabels(true);
        jThresholdSlider.setPaintTicks(true);

        javax.swing.GroupLayout jImageProcPanelLayout = new javax.swing.GroupLayout(jImageProcPanel);
        jImageProcPanel.setLayout(jImageProcPanelLayout);
        jImageProcPanelLayout.setHorizontalGroup(
            jImageProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jImageProcPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jImageProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jImageProcPanelLayout.createSequentialGroup()
                        .addComponent(jThresholdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jThresholdSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                    .addGroup(jImageProcPanelLayout.createSequentialGroup()
                        .addComponent(jFrameSubLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(jFrameSubNeverRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(jFrameSubOnceRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(jFrameSubAlwaysRadioButton)))
                .addContainerGap())
        );
        jImageProcPanelLayout.setVerticalGroup(
            jImageProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jImageProcPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jImageProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFrameSubLabel)
                    .addComponent(jFrameSubAlwaysRadioButton)
                    .addComponent(jFrameSubOnceRadioButton)
                    .addComponent(jFrameSubNeverRadioButton))
                .addGroup(jImageProcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jImageProcPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jThresholdLabel))
                    .addGroup(jImageProcPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jThresholdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jImageProcPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAddressPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                        .addComponent(jCancelButton)
                        .addGap(4, 4, 4)
                        .addComponent(jOKButton))
                    .addComponent(jCameraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCameraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jImageProcPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOKButton)
                    .addComponent(jCancelButton)
                    .addComponent(jStatusLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void jOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKButtonActionPerformed
    final Event e = new Event();
    for(Listener l : listeners) 
    {
        l.finished(e);
        if(e.isCancelled()) break;
    }
}//GEN-LAST:event_jOKButtonActionPerformed

private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
    final Event e = new Event();
    for(Listener l : listeners) l.cancelled(e);
}//GEN-LAST:event_jCancelButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup frameSubButtonGroup;
    private javax.swing.JCheckBox jFlipHorizontalCheckBox;
    private javax.swing.JCheckBox jFlipVerticalCheckBox;
    private javax.swing.JRadioButton jFrameSubAlwaysRadioButton;
    private javax.swing.JLabel jFrameSubLabel;
    private javax.swing.JRadioButton jFrameSubNeverRadioButton;
    private javax.swing.JRadioButton jFrameSubOnceRadioButton;
    private final javax.swing.JComboBox jFramerateComboBox = new javax.swing.JComboBox();
    private final javax.swing.JTextField jHostTextField = new javax.swing.JTextField();
    private javax.swing.JSpinner jPortSpinner;
    private javax.swing.JComboBox jResolutionComboBox;
    private final javax.swing.JLabel jStatusLabel = new javax.swing.JLabel();
    private javax.swing.JLabel jThresholdLabel;
    private javax.swing.JSlider jThresholdSlider;
    // End of variables declaration//GEN-END:variables
    private Collection<Listener> listeners = new ArrayList<Listener>();
 
    
    private static class ComboBoxRenderer extends JLabel implements ListCellRenderer 
    {    
        public ComboBoxRenderer() 
        {
            setOpaque(true);
            setHorizontalAlignment(CENTER);//RIGHT);
            setVerticalAlignment(CENTER);
        }

        /*
         * This method finds the image and text corresponding
         * to the selected value and returns the label, set up
         * to display the text and image.
         */
        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) 
        {
            //Get the selected index. (The index param isn't
            //always valid, so just use the value.)
            //int selectedIndex = ((Integer)value).intValue();

            if (isSelected) 
            {
                setBackground(list.getSelectionBackground());
                setForeground(list.getSelectionForeground());
            } 
            else 
            {
                setBackground(list.getBackground());
                setForeground(list.getForeground());
            }

            setText(value.toString());

            return this;
        }    
    }
}
