/*
 * ServerUI.java
 *
 * Created on July 13, 2007, 12:07 AM
 */

package demo.tuio;

import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.WindowConstants;

/**
 *
 * @author  gestalt
 */
public class ServerUI extends javax.swing.JFrame {
    
    private final Image icon;        

    /** Creates new form ServerUI */
    ServerUI() 
    {
        {
            Image image = null;
            try {
                image = ImageIO.read(ServerUI.class.getResource("/de/telekom/Icon.png"));
            }
            catch (IOException ioe) {
            }
            icon = image;
        }   
        initComponents();
    }
    
    private void exit()
    {
        System.exit(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        final javax.swing.ButtonGroup frameSubButtonGroup = new javax.swing.ButtonGroup();
        final javax.swing.JButton jOKButton = new javax.swing.JButton();
        final javax.swing.JButton jCancelButton = new javax.swing.JButton();
        final javax.swing.JToggleButton jImageViewToggleButton = new javax.swing.JToggleButton();
        final javax.swing.JLabel jHostLabel = new javax.swing.JLabel();
        final javax.swing.JTextField jHostTextField = new javax.swing.JTextField();
        final javax.swing.JLabel jPortLabel = new javax.swing.JLabel();
        final javax.swing.JSpinner jPortSpinner = new javax.swing.JSpinner();
        final javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        final javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        final javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        final javax.swing.JLabel jResolutionLabel = new javax.swing.JLabel();
        final javax.swing.JComboBox jResolutionComboBox = new javax.swing.JComboBox();
        final javax.swing.JComboBox jFrameRateComboBox = new javax.swing.JComboBox();
        final javax.swing.JLabel jFrameRateLabel = new javax.swing.JLabel();
        final javax.swing.JLabel jFlipLabel = new javax.swing.JLabel();
        final javax.swing.JCheckBox jHorizontalCheckBox = new javax.swing.JCheckBox();
        final javax.swing.JCheckBox jVerticalCheckBox = new javax.swing.JCheckBox();
        final javax.swing.JSeparator jSeparator2 = new javax.swing.JSeparator();
        final javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        final javax.swing.JLabel jFrameSubractionLabel = new javax.swing.JLabel();
        final javax.swing.JRadioButton jAlwaysRadioButton = new javax.swing.JRadioButton();
        final javax.swing.JRadioButton jOnceRadioButton = new javax.swing.JRadioButton();
        final javax.swing.JRadioButton jNeverRadioButton = new javax.swing.JRadioButton();
        final javax.swing.JLabel jThresholdLabel = new javax.swing.JLabel();
        final javax.swing.JSlider jThresholdSlider = new javax.swing.JSlider();
        final javax.swing.JSeparator jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Multi-T-ouch: TUIO Server");
        setIconImage(icon);
        setLocationByPlatform(true);
        setName("frameTUIO"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jOKButton.setText("OK");

        jCancelButton.setText("Cancel");

        jImageViewToggleButton.setText("View Image");

        jHostLabel.setLabelFor(jHostTextField);
        jHostLabel.setText("Host:");

        jHostTextField.setText("localhost");

        jPortLabel.setText("Port:");

        jPortSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(jPortSpinner, "#"));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+1));
        jLabel1.setText("Internet Socket Address");

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+1));
        jLabel2.setText("Camera Settings");

        jResolutionLabel.setText("Resolution:");

        jResolutionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " 1024 x  768" }));

        jFrameRateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  30" }));

        jFrameRateLabel.setText("Frame-Rate:");

        jFlipLabel.setText("Flip:");

        jHorizontalCheckBox.setText("horizontal");
        jHorizontalCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jVerticalCheckBox.setText("vertical");
        jVerticalCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()+1));
        jLabel3.setText("Image Processing");

        jFrameSubractionLabel.setText("Frame-Subtraction:");

        frameSubButtonGroup.add(jAlwaysRadioButton);
        jAlwaysRadioButton.setText("always");
        jAlwaysRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        frameSubButtonGroup.add(jOnceRadioButton);
        jOnceRadioButton.setSelected(true);
        jOnceRadioButton.setText("once");
        jOnceRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        frameSubButtonGroup.add(jNeverRadioButton);
        jNeverRadioButton.setText("never");
        jNeverRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jThresholdLabel.setText("Threshold:");

        jThresholdSlider.setMajorTickSpacing(50);
        jThresholdSlider.setMaximum(255);
        jThresholdSlider.setMinorTickSpacing(5);
        jThresholdSlider.setPaintLabels(true);
        jThresholdSlider.setPaintTicks(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jHostLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jHostTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPortLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPortSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(335, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jResolutionLabel)
                            .addComponent(jFlipLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jResolutionComboBox, 0, 160, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jFrameRateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFrameRateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jHorizontalCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(jVerticalCheckBox)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(326, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jThresholdLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(jThresholdSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFrameSubractionLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                        .addComponent(jNeverRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(jOnceRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(jAlwaysRadioButton)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jImageViewToggleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHostLabel)
                    .addComponent(jPortSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPortLabel)
                    .addComponent(jHostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jResolutionLabel)
                    .addComponent(jFrameRateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFrameRateLabel)
                    .addComponent(jResolutionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFlipLabel)
                    .addComponent(jHorizontalCheckBox)
                    .addComponent(jVerticalCheckBox))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFrameSubractionLabel)
                    .addComponent(jAlwaysRadioButton)
                    .addComponent(jOnceRadioButton)
                    .addComponent(jNeverRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jThresholdLabel)
                    .addComponent(jThresholdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jImageViewToggleButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelButton)
                    .addComponent(jOKButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-473)/2, (screenSize.height-501)/2, 473, 501);
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    if(!systemTray()) floatingWindow(); 
}//GEN-LAST:event_formWindowClosed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() {
                new ServerUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    // <editor-fold defaultstate="collapsed" desc=" System Tray ">
        
    private boolean systemTray()
    {
        if (icon == null || !SystemTray.isSupported()) return false;
        
        final SystemTray tray = SystemTray.getSystemTray();


        final ActionListener exitListener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e)
            {
                exit();
            }
        };

        final PopupMenu popup = new PopupMenu();

        //final CheckboxMenuItem cameraItem = new CheckboxMenuItem("Camera");
        final MenuItem stopItem = new MenuItem("Stop");
        stopItem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e)
            {
                exit();
            }
        });

        final MenuItem exitItem = new MenuItem("Exit");
        exitItem.addActionListener(exitListener);

        //popup.add(cameraItem);
        //popup.addSeparator();
        popup.add(exitItem);

        final TrayIcon trayIcon = new TrayIcon(icon, "MultiTouch: TUIO Server", popup);
        trayIcon.setImageAutoSize(true);

        try {
            tray.add(trayIcon);
        }
        catch (AWTException e) {
            return false;
        }

        return true;
    }

    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc=" Floating Window ">
    private void floatingWindow()
    {
        final JDialog jDialog = new JDialog();
        jDialog.setLocationByPlatform(true);
        jDialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        jDialog.setTitle("Multi-T-ouch: TUIO Server");

        jDialog.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e)
            {
                exit();
            }
        });

        //final JToggleButton jCameraButton = new JToggleButton("Camera");
        final JButton jStopButton = new JButton("Stop");
        jStopButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e)
            {
                exit();
            }
        });

        jDialog.getContentPane().setLayout(new GridLayout(1, 1));
        //jDialog.getContentPane().setLayout(new GridLayout(2, 1));
        //jDialog.getContentPane().add(jCameraButton);
        jDialog.getContentPane().add(jStopButton);

        jDialog.setPreferredSize(new Dimension(240, 120));
        jDialog.pack();
        jDialog.setResizable(false);
        jDialog.setVisible(true);
    }

    // </editor-fold>    
    
}
